name: Deploy BBYOUTH to VPS
on:
  workflow_dispatch: # Manual trigger for development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.1'
    - name: Install dependencies
      run: npm ci
    - name: Build Next.js app
      run: npm run build
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
    - name: Deploy to VPS
      run: |
        ssh -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /var/www/bbyouths
          git fetch origin
          git reset --hard origin/main
          npm ci --production
          npm run build
          pm2 restart bbyouths || pm2 start npm --name bbyouths -- start
          pm2 save
        EOF
    - name: Verify deployment
      run: |
        ssh -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          pm2 list | grep bbyouths || echo "PM2 process not running"
          curl -I http://localhost:3000 || echo "App not responding on 3000"
        EOF